stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: ${DOCKER_REGISTRY}/python:3.11.9-slim
  script:
    - pip install -r requirements.txt
    - python -m pytest

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker build -t churn-api:latest .

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f infra/k8s/
  only:
    - main
